# vim:ft=ansible:
version: '3'
services:
  php74-fpm:
    build:
      context: ./7.4/fpm/
      dockerfile: Dockerfile
    image: solusik8s/php:7.4-fpm
  php81-cli:
    build:
      context: ./8.1/cli/
      dockerfile: Dockerfile
    image: solusik8s/php:8.1-cli
  php81-fpm:
    build:
      context: ./8.1/fpm/
      dockerfile: Dockerfile
    image: solusik8s/php:8.1-fpm
  php81-audit:
    build:
      context: ./8.1/audit/
      dockerfile: Dockerfile
    image: solusik8s/php:8.1-audit.R2
  php81-ubuntu2204:
    build:
      context: ./8.1/ubuntu-22.04/
      dockerfile: Dockerfile
    image: solusik8s/php:8.1-ubuntu-22.04
    ports:
      - 8080:80
